version: '3.8'
services:
  php-fpm:
    build: ./config/php
    container_name: php-fpm
    volumes:
      - ./backend:/var/www/html
      - ./config/php/php.ini:/usr/local/etc/php/php.ini
    networks:
      - app-network

  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "3000:80"
    volumes:
      - ./backend:/var/www/html
      - ./frontend/dist:/usr/share/nginx/html
      - ./config/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php-fpm
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
